### PR TITLE
chore: port module to our current standard

### PR DESCRIPTION
**Pull request by ralgozino**
- update the module's documentation to our current standard
- left some FIXME comments to be worked on during the PR review with @lzecca78
  because I don't know the details.

### CODE REVIEW

**Review by lzecca78 — COMMENTED** [review]
@ralgozino , if you need an help for finishing up the doc, just ping me, we can arrange it

**Comment by ralgozino** [comment]
Hi @lzecca78 ,

I've done all that I could, if you can take over and fill the FIXMEs with the missing information that would be great!
thanks!

**Comment by lzecca78** [comment]
Hi @ralgozino, I guess to have added everything you've pointed out.
Please let me know if everything is okay or if something is still to be added.

**Comment by ralgozino** [comment]
Thank you @lzecca78

I made some styling changes to the copy and some minor markdown linting on top of your changes.
There's probably room for improvement but the content lgtm for a first version.

**Pull request merged**
